version: '3'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - ToDo-APP/var/lib/docker/volumes/volume2/_data
    environment:
       MONGO_INITDB_ROOT_USERNAME: admin
       MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - network2
    hostname: host1
  todoapp:
    build: .
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    networks:
      - network2
networks:
  network2:
volumes:
  volume2:
