version: '3'
services:
  mongodb:
    image: mongo:latest
    volumes:
      -  volume1:/data/db
    environment:
       MONGO_INITDB_ROOT_USERNAME: myuser
       MONGO_INITDB_ROOT_PASSWORD: mypassword
    networks:
      - network1
    hostname: my_host

  todoapp:
    build: .
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    networks:
      - network1
networks:
  network1:
  
volumes:
  volume1:
