version: '3'
services:
  mongodb:
    image: mongo:latest
    volumes:
      -  todo-volume2:/data/db
    environment:
       MONGO_INITDB_ROOT_USERNAME: myuser
       MONGO_INITDB_ROOT_PASSWORD: mypassword
    networks:
      - network2
    hostname: my_host
  todoapp:
    build: .
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    networks:
      - network2
networks:
  network2:
volumes:
  volume2:
