version: '3.8'

services:
  node_todo:
    build: ./ToDo-APP
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/todo

  mongo:
    ports:
      - "27017:27017"
    volumes:
      - volume1

volumes:
  mongo_data: